from __future__ import annotations

from datetime import datetime
from typing import List, Literal, Optional

from pydantic import BaseModel, Field

Difficulty = Literal["easy", "medium", "hard"]
VulnType = Literal[
    "xss",
    "sqli",
    "ssrf",
    "rce",
    "path_traversal",
    "command_injection",
    "insecure_deserialization",
    "none",
]

FrontendDifficulty = Literal["EASY", "MEDIUM", "HARD"]
FrontendLanguage = Literal["javascript", "python", "java", "go", "php"]
FrontendVulnType = Literal[
    "XSS",
    "SQL_INJECTION",
    "SSRF",
    "RCE",
    "PATH_TRAVERSAL",
    "COMMAND_INJECTION",
    "INSECURE_DESERIALIZATION",
    "SAFE",
]
FrontendSystemName = Literal[
    "O2",
    "NAVIGATION",
    "SHIELDS",
    "REACTOR",
    "COMMUNICATIONS",
    "ELECTRICAL",
    "MEDBAY",
    "SECURITY",
    "WEAPONS",
    "ADMIN",
]
FrontendTaskStatus = Literal["pending", "completed", "failed", "current"]

# Model for difficulty configuration
class DifficultyConfig(BaseModel):
    base_time_seconds: int
    penalty_seconds: int
    vuln_density: float
    complexity_tag: Literal["low", "medium", "high"]
    hints_allowed: bool


#configurations based on the difficulty level 
DIFFICULTY_CONFIGS: dict[Difficulty, DifficultyConfig] = {
    "easy": DifficultyConfig(
        base_time_seconds=120,
        penalty_seconds=5,
        vuln_density=0.4,
        complexity_tag="low",
        hints_allowed=True,
    ),
    "medium": DifficultyConfig(
        base_time_seconds=90,
        penalty_seconds=8,
        vuln_density=0.6,
        complexity_tag="medium",
        hints_allowed=True,
    ),
    "hard": DifficultyConfig(
        base_time_seconds=60,
        penalty_seconds=12,
        vuln_density=0.8,
        complexity_tag="high",
        hints_allowed=False,
    ),
}


# model for tasks generated by claude 
class TaskSchema(BaseModel):
    id: str
    system_name: str
    code: str
    is_vulnerable: bool
    vulnerability_type: VulnType
    difficulty: Difficulty
    language: Optional[str] = None
    vulnerability_line: Optional[int] = None
    hints: Optional[List[str]] = None


class TaskPublicSchema(BaseModel):
    id: str
    system_name: str
    code: str
    difficulty: Difficulty
    language: Optional[str] = None
    hints: Optional[List[str]] = None


class SessionCreateRequest(BaseModel):
    difficulty: Difficulty
    task_count: int = Field(ge=1, le=10)

# response model for session creation with the configured parameters based on difficulty
class SessionCreateResponse(BaseModel):
    session_id: str
    created_at: datetime
    difficulty: Difficulty
    config: DifficultyConfig

#response model for listing tasks in a session
class TaskListResponse(BaseModel):
    session_id: str
    tasks: List[TaskPublicSchema]

#schema for each answer submitted by user
class AnswerSchema(BaseModel):
    task_id: str
    user_choice: Literal["clean", "sabotaged"]

#request model for submitting answers
class SubmitAnswersRequest(BaseModel):
    answers: List[AnswerSchema]

#final response after submitting answers
class SubmitAnswersResponse(BaseModel):
    correct: int
    incorrect: int
    missed_task_ids: List[str]

#audit log from hacktron 
class AuditLogSchema(BaseModel):
    task_id: str
    raw_log: str
    findings: Optional[List[str]] = None

# Mentor report schema from claude 
class MentorReportSchema(BaseModel):
    summary: str

#final response with claude report
class FinishResponse(BaseModel):
    session_id: str
    score: int
    missed_task_ids: List[str]
    audit_logs: List[AuditLogSchema]
    mentor_report: MentorReportSchema

# Request and Response models for Frontend Task Generation and Auditing
class GenerateSnippetsRequest(BaseModel):
    language: FrontendLanguage
    difficulty: FrontendDifficulty
    complexityLevel: Literal["basic", "intermediate", "advanced"]
    count: int = Field(ge=1, le=10)

# model for each frontend task
class FrontendTask(BaseModel):
    id: str
    systemName: FrontendSystemName
    code: str
    language: FrontendLanguage
    isVulnerable: bool
    vulnerabilityType: FrontendVulnType
    vulnerabilityLine: Optional[int] = None
    status: FrontendTaskStatus = "pending"
    explanation: Optional[str] = None
    hints: Optional[List[str]] = None

# response model for generated snippets
class GenerateSnippetsResponse(BaseModel):
    tasks: List[FrontendTask]
    error: Optional[str] = None

# model for each audit finding
class AuditFinding(BaseModel):
    taskId: str
    systemName: FrontendSystemName
    vulnerability: FrontendVulnType
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    description: str
    codeLocation: dict
    remediation: str
    codeSnippet: Optional[str] = None

# model for the complete audit report
class AuditReport(BaseModel):
    findings: List[AuditFinding]
    summary: str
    audioUrl: Optional[str] = None

# request model for auditing tasks
class AuditRequest(BaseModel):
    tasks: List[FrontendTask]
    language: FrontendLanguage

# response model for audit report
class AuditResponse(BaseModel):
    report: AuditReport
    error: Optional[str] = None

# Request and Response models for Text-to-Speech (TTS) Integration
class TTSRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=5000, description="Text to convert to speech (max 5000 chars)")
    voiceId: Optional[str] = Field(None, max_length=100, description="Voice ID or preset name")
    voiceSettings: Optional[dict] = None

# Response model for TTS output
class TTSResponse(BaseModel):
    audioUrl: str
    duration: Optional[float] = None
    error: Optional[str] = None
